[package]
name = "rhxplayer-native"
version = "1.0.2"
authors = ["RinCynar"]
build = "build.rs"
edition = "2021"

[lib]
name = "native"
crate-type = ["cdylib"]

[dependencies.neon]
git = "https://github.com/neon-bindings/neon"
branch = "main"
default-features = false
features = ["napi-7"]

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio"
rev = "ee73f6d"
default-features = false
features = ["symphonia-flac", "symphonia-mp3", "symphonia-wav"]

[target.'cfg(not(target_os = "macos"))'.dependencies]
souvlaki = "0.7.3"

[target.'cfg(all(target_os = "windows", any(target_arch = "x86_64", target_arch = "x86")))'.dependencies]
raw-window-handle = "0.6.2"
winit = "0.30.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.56.0"
features = ["Win32_Foundation", "Win32_System_Threading"]
